# Author: InboundHalo
# Discord: inboundhalo
# ##### ##### ##### ##### ##### ##### #####
# Links
# DamageCause List: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/EntityDamageEvent.DamageCause.html
# ##### ##### ##### ##### ##### ##### #####


cancel-interact: # Prevents placing and interacting (right click)
  - WARPED_TRAPDOOR
  - CHEST
  - TRAPPED_CHEST
  - BARREL
  - ANVIL
  - SMOKER
  - OAK_BUTTON
  - SPRUCE_FENCE_GATE
  - FARMLAND

cancel-damage: # List: DamageCause
  - FALL
  - FIRE
  - FIRE_TICK
  - FLY_INTO_WALL
  - FREEZE
  - HOT_FLOOR
  - LAVA
